replicaCount: 1
image: ollama/ollama
#
# You will eventually need all 3 of these to group inference workloads together
# on GPU nodes.
#
nodeSelector: {}
tolerations: []
affinity: {}
redis:
  replicas: 1
  port: 6379
